name: Deploy Fronted CRM dev

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build frontend
        run: npm run build_dev

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          username: ${{ secrets.SERVER_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          source: "."
          target: "/var/www/fastuser/data/www/lk.dev.skilla.ru/"
          strip_components: 1
          rm: true
          ignore: |
            node_modules/
            git/
            github/
      - name: Restart app with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          username: ${{ secrets.SERVER_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            cd /var/www/fastuser/data/www/lk.dev.skilla.ru/
            npm install --production --legacy-peer-deps
